# Generated by Django 5.0.3 on 2024-03-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('wattage', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Bulb', 'Bulb'), ('Air Conditioner', 'Air Conditioner'), ('Bathroom Appliances', 'Bathroom Appliances'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Bedroom Appliances', 'Bedroom Appliances'), ('TV', 'TV')], max_length=100)),
                ('usage_per_hour', models.FloatField()),
                ('carbon_footprint', models.FloatField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BathroomUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heater_wattage', models.IntegerField()),
                ('heater_quantity', models.IntegerField()),
                ('january', models.IntegerField()),
                ('february', models.IntegerField()),
                ('march', models.IntegerField()),
                ('april', models.IntegerField()),
                ('may', models.IntegerField()),
                ('june', models.IntegerField()),
                ('july', models.IntegerField()),
                ('august', models.IntegerField()),
                ('september', models.IntegerField()),
                ('october', models.IntegerField()),
                ('november', models.IntegerField()),
                ('december', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BedroomApplianceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_wattage', models.IntegerField()),
                ('fan_quantity', models.IntegerField()),
                ('january', models.IntegerField()),
                ('february', models.IntegerField()),
                ('march', models.IntegerField()),
                ('april', models.IntegerField()),
                ('may', models.IntegerField()),
                ('june', models.IntegerField()),
                ('july', models.IntegerField()),
                ('august', models.IntegerField()),
                ('september', models.IntegerField()),
                ('october', models.IntegerField()),
                ('november', models.IntegerField()),
                ('december', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bulb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulb_type', models.CharField(choices=[('LED', 'LED'), ('Fluorescent', 'Fluorescent'), ('CFL', 'CFL'), ('Smart', 'Smart Light'), ('Halogen', 'Halogen')], max_length=20)),
                ('january', models.IntegerField()),
                ('february', models.IntegerField()),
                ('march', models.IntegerField()),
                ('april', models.IntegerField()),
                ('may', models.IntegerField()),
                ('june', models.IntegerField()),
                ('july', models.IntegerField()),
                ('august', models.IntegerField()),
                ('september', models.IntegerField()),
                ('october', models.IntegerField()),
                ('november', models.IntegerField()),
                ('december', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FanMonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_type', models.CharField(choices=[('Main', 'Main'), ('Pedestrial', 'Pedestrial'), ('Table', 'Table'), ('Lightweight', 'Lightweight')], max_length=20)),
                ('january', models.IntegerField()),
                ('february', models.IntegerField()),
                ('march', models.IntegerField()),
                ('april', models.IntegerField()),
                ('may', models.IntegerField()),
                ('june', models.IntegerField()),
                ('july', models.IntegerField()),
                ('august', models.IntegerField()),
                ('september', models.IntegerField()),
                ('october', models.IntegerField()),
                ('november', models.IntegerField()),
                ('december', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KitchenAppliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhaust_duration', models.IntegerField()),
                ('exhaust_wattage', models.IntegerField()),
                ('exhaust_quantity', models.IntegerField()),
                ('fridge_duration', models.IntegerField()),
                ('fridge_wattage', models.IntegerField()),
                ('fridge_quantity', models.IntegerField()),
                ('oven_duration', models.IntegerField()),
                ('oven_wattage', models.IntegerField()),
                ('oven_quantity', models.IntegerField()),
                ('induction_duration', models.IntegerField()),
                ('induction_wattage', models.IntegerField()),
                ('induction_quantity', models.IntegerField()),
                ('grinder_duration', models.IntegerField()),
                ('grinder_wattage', models.IntegerField()),
                ('grinder_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user_profile_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_hours', models.IntegerField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appliance')),
            ],
        ),
    ]
