# Generated by Django 5.0.3 on 2024-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulb',
            name='bulb_type',
            field=models.CharField(choices=[('LED', 'LED'), ('Fluorescent', 'Fluorescent'), ('CFL', 'CFL'), ('Smart', 'Smart Light'), ('Halogen', 'Halogen')], default='LED', max_length=20),
        ),
    ]
