# Generated by Django 5.0.4 on 2024-04-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bathroomappliance_bedroomappliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='bathroom_appliance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bathroomappliance'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='bedroom_appliance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bedroomappliance'),
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fan_monthly_usage',
        ),
        migrations.AlterField(
            model_name='appliance',
            name='kitchen_appliance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kitchenappliance'),
        ),
        migrations.RemoveField(
            model_name='usage',
            name='appliance',
        ),
        migrations.DeleteModel(
            name='BathroomUsage',
        ),
        migrations.DeleteModel(
            name='BedroomApplianceUsage',
        ),
        migrations.DeleteModel(
            name='FanMonthlyUsage',
        ),
        migrations.DeleteModel(
            name='KitchenAppliances',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
