# Generated by Django 5.0.4 on 2024-04-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_appliance_bathroom_appliance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroomappliance',
            name='bathroom_name',
        ),
    ]
