# Generated by Django 5.0.3 on 2024-04-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_bathroomappliance_bathroom_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appliance',
        ),
    ]
